// This is an automatically generated file. Please do not edit this file manually.
'use server';

/**
 * @fileOverview Automatically assigns reported issues to contractors based on their location, skills, and current workload.
 *
 * - assignTaskToContractor - A function that automatically assigns tasks to contractors.
 * - AssignTaskToContractorInput - The input type for the assignTaskToContractor function.
 * - AssignTaskToContractorOutput - The return type for the assignTaskToContractor function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AssignTaskToContractorInputSchema = z.object({
  issueType: z.string().describe('The type of the reported issue (e.g., pothole, broken street light).'),
  issueLocation: z.string().describe('The geographical location of the reported issue.'),
  contractorSkills: z.array(z.string()).describe('A list of skills required to resolve the issue.'),
  contractorAvailability: z.boolean().describe('Whether or not the contractor is available to be assigned tasks.'),
  contractorCurrentLoad: z.number().describe('The number of tasks the contractor is currently assigned.'),
  contractorMaxTasks: z.number().describe('The maximum number of tasks the contractor can be assigned.'),
});
export type AssignTaskToContractorInput = z.infer<typeof AssignTaskToContractorInputSchema>;

const AssignTaskToContractorOutputSchema = z.object({
  contractorId: z.string().describe('The ID of the contractor to whom the task is assigned.'),
  reason: z.string().describe('The reasoning behind assigning the task to the selected contractor.'),
});
export type AssignTaskToContractorOutput = z.infer<typeof AssignTaskToContractorOutputSchema>;

export async function assignTaskToContractor(input: AssignTaskToContractorInput): Promise<AssignTaskToContractorOutput> {
  return automaticTaskAssignmentFlow(input);
}

const automaticTaskAssignmentPrompt = ai.definePrompt({
  name: 'automaticTaskAssignmentPrompt',
  input: {schema: AssignTaskToContractorInputSchema},
  output: {schema: AssignTaskToContractorOutputSchema},
  prompt: `You are an expert in task assignment for civic issues. Given an issue report, your goal is to select the most suitable contractor to resolve the issue.

Issue Type: {{{issueType}}}
Issue Location: {{{issueLocation}}}
Contractor Skills: {{#each contractorSkills}}{{{this}}}, {{/each}}
Contractor Availability: {{{contractorAvailability}}}
Contractor Current Load: {{{contractorCurrentLoad}}}
Contractor Max Tasks: {{{contractorMaxTasks}}}

Based on these factors, determine the most appropriate contractor ID to assign this task to, and explain your reasoning. Return the contractor ID and reasoning in the required JSON format.
`,
});

const automaticTaskAssignmentFlow = ai.defineFlow(
  {
    name: 'automaticTaskAssignmentFlow',
    inputSchema: AssignTaskToContractorInputSchema,
    outputSchema: AssignTaskToContractorOutputSchema,
  },
  async input => {
    const {output} = await automaticTaskAssignmentPrompt(input);
    return output!;
  }
);
